{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n>       assert func(3)==5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\ntest_project1.py:6: AssertionError"}, "start": 1676887203872, "stop": 1676887203872, "uuid": "a14b6204-d580-4501-9d00-5833b156642b", "historyId": "9defb98ad16bf81690babcb7c6ee6f8c", "testCaseId": "ae9ab8ec08a03ce70233d5218e532cec", "fullName": "test_project1#test_answer", "labels": [{"name": "suite", "value": "test_project1"}, {"name": "host", "value": "DESKTOP-KG3DMFK"}, {"name": "thread", "value": "288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_project1"}]}