{"name": "test_one", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'a' in 'this'", "trace": "self = <test_class.TestClass object at 0x0000028DFF39D630>\n\n    def test_one(self):\n        x = \"this\"\n>       assert 'a' in x\nE       AssertionError: assert 'a' in 'this'\n\ntest_class.py:6: AssertionError"}, "start": 1676887134695, "stop": 1676887134695, "uuid": "96ee42e1-e240-4919-aee7-460062e61f91", "historyId": "b930130edd697e7698e0589d85b3e75d", "testCaseId": "97e3de7536fc1c04652183eb06586e9e", "fullName": "test_class.TestClass#test_one", "labels": [{"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-KG3DMFK"}, {"name": "thread", "value": "18944-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_class"}]}